updated build file

diff --git a/.github/workflows/strip-miniaudio.yml b/.github/workflows/strip-miniaudio.yml
--- a/.github/workflows/strip-miniaudio.yml
+++ b/.github/workflows/strip-miniaudio.yml
@@ -35,25 +35,25 @@ jobs:
             exit 1
           fi
       
-#      # Run unifdef
-#      - name: Run unifdef
-#        continue-on-error: true # unifdef returns 1 if content changed
-#        run: |
-#          unifdef \
-#              -DMA_NO_DECODING -DMA_NO_ENCODING \
-#              -DMA_NO_WAV -DMA_NO_FLAC -DMA_NO_MP3 \
-#              -DMA_NO_ENGINE -DMA_NO_THREADING -DMA_NO_RESOURCE_MANAGER \
-#              -DMA_NO_NODE_GRAPH -DMA_NO_GENERATION \
-#              miniaudio.h > miniaudio_processed.h
-#              if [ $? -eq 2 ]; then
-#                echo "Error: unifdef encountered a problem"
-#                exit 2
-#              fi
-#              mv miniaudio_processed.h miniaudio.h
-#
-#      # Remove block comments
-#      - name: Remove block comments
-#        run: sed -i '/\/\*/,/\*\//d' miniaudio.h
+     # Run unifdef
+     - name: Run unifdef
+       continue-on-error: true # unifdef returns 1 if content changed
+       run: |
+         unifdef \
+             -DMA_NO_DECODING -DMA_NO_ENCODING \
+             -DMA_NO_WAV -DMA_NO_FLAC -DMA_NO_MP3 \
+             -DMA_NO_ENGINE -DMA_NO_THREADING -DMA_NO_RESOURCE_MANAGER \
+             -DMA_NO_NODE_GRAPH -DMA_NO_GENERATION \
+             miniaudio.h > miniaudio_processed.h
+             if [ $? -eq 2 ]; then
+               echo "Error: unifdef encountered a problem"
+               exit 2
+             fi
+             mv miniaudio_processed.h miniaudio.h
+
+    #  # Remove block comments
+    #  - name: Remove block comments
+    #    run: sed -i '/\/\*/,/\*\//d' miniaudio.h
 
       # Commit and push changes
       - name: Commit and push changes
